### ISSUE TITLE
ngbDropdownToggle in the header component not working in using router.navigate

### ISSUE THREAD

**Issue by joshting** [start-angular/SB-Admin-BS4-Angular-4#101]
The original code uses [routerLink] to go the the dashboard from login page.  Of course in a real scenario, it will have to be authenticated and then if successful routed to the landing page.  So, after successful authentication, I use router.navigate to route to /dashboard.  The problem is I can't click on the header menu (where logout is).  If refresh the page.. then everything's normal again.  Not sure what is the difference in the behaviour of [routerLink] and router.navigate...

**Comment by nitinkumarmishra** [comment]
use router.navigate([dashboard']) will work fine.
![image](https://user-images.githubusercontent.com/14124584/27514106-14908374-599e-11e7-8f65-719e7442e5b0.png)
