### ISSUE TITLE
router animation breaks scrolling

### ISSUE THREAD

**Issue by tubaman** [start-angular/SB-Admin-BS4-Angular-4#106]
The [router animation commit](https://github.com/start-angular/SB-Admin-BS4-Angular-4/commit/2a43faf23f84907698a10b95230b4b3ba7b65823) breaks page scrolling.  You can no longer scroll the page up/down.

**Comment by JamesCyrilJordan** [comment]
I commented out the browser animation import as a temporary workaround to this.
//import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
and in the imports array
//BrowserAnimationsModule,

**Comment by nitinkumarmishra** [comment]
Fixed scroll issue
