### ISSUE TITLE
not working dist index.html file showing this error

### ISSUE THREAD

**Issue by suresh2018** [start-angular/SB-Admin-BS4-Angular-4#108]
normally working fine ng serve.
node v=   >6.0    npm v=    >3.0
ng build -> dist -> index.html i run this file showing this error .How to fix this issue.please help me.

![image](https://user-images.githubusercontent.com/30258184/28309428-f891b586-6bc6-11e7-8ca9-b6cdf2f156dd.png)

**Comment by AlainD-** [comment]
I think that you still have to **serve** the dist folder anyway.

**Comment by suresh2018** [comment]
Nop .. i opened dist folder index.html

**Comment by AlainD-** [comment]
Yes I understood what you did. But what I mean is you have to serve the built index.html in a web application server (Apache for instance), and not open it directly from the file system explorer (double click).

**Comment by suresh2018** [comment]
I hosted in my local IIS server and also Try http-server /dist .
when opened in browser machine hanging ...

**Comment by suresh2018** [comment]
load children not working in production build

**Comment by nitinkrmr** [comment]
Lazy loading is working in the production you can see in following screenshot image
![image](https://user-images.githubusercontent.com/14124584/28702265-7dedb388-7379-11e7-9a12-adca5a45c66e.png)
