### ISSUE TITLE
unable to run npm run build

### ISSUE THREAD

**Issue by terrysclaw** [start-angular/SB-Admin-BS4-Angular-4#111]
when i try to run run build caused error.

[npm-debug.zip](https://github.com/start-angular/SB-Admin-BS4-Angular-4/files/1172487/npm-debug.zip)

**Comment by nitinkrmr** [comment]
run `npm run build` command if its failing then try to update @angular/cli and let me know if you are facing any issue.

**Comment by chrisplusplus** [comment]
Same issue here.  I have the latest version of npm and node

**Comment by nitinkrmr** [comment]
update `@angular/cli` version and then try `npm run build`

**Comment by Midhilaj** [comment]
npm install -g @latest
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@latest": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/midhilaj/.npm/_logs/2017-07-29T04_42_27_104Z-debug.log

**Comment by Midhilaj** [comment]
ng build work for me

**Comment by AlainD-** [comment]
Seriously @Midhilaj?! Can't you see that @chrisplusplus forgot the package name in the command line?!

The corrected command line is `npm install -g @angular/cli@latest`

Regards.

**Comment by terrysclaw** [comment]
update @angular/cli version and then try npm run build

ng build work for me now

**Comment by arvindsanwaldev** [comment]
I have updated angular-cli with latest version but still unable to build.

Getting Error : 

ERROR in Template parse errors:
Can't bind to 'up' since it isn't a known property of 'div'. ("
            </div>
            <div class="col text-right">
                <div ngbDropdown [ERROR ->][up]="true" class="d-inline-block">
                    <button class="btn btn-outline-primary" id="d"): ng:///home/arvind/projects/learing/SB-Admin-BS4-Angular-4/src/app/layout/bs-component/components/dropdown/dropdown.component.html@15:33

**Comment by BenjaminRen** [comment]
@arvindsanwaldev 
\src\app\layout\bs-component\components\dropdown\dropdown.component.html
delete '[up]' in that div

**Comment by bjakubiak** [comment]
Or even better replace `[up]="true"` with `placement="top-right"` which makes dropdown drop up. https://ng-bootstrap.github.io/#/components/dropdown/api

**Comment by BenjaminRen** [comment]
It's ok with npm start. But when I try npm run build I got error.
It's my node npm version:
node v8.4.0
npm  v5.4.0
angular cli 1.2

I've reinstalled cli, and changed ngbootstrap version, It doesn't work.
(new clone without any change,is the warning normal?)
show on screen:
`11% building modules 9/10 modules 1 active ...S4-Angular-4-demo/src/styles/app.scssWarning: Can't resolve all parameters for NgbModalRef in /home/rendiqi/work/SB-Admin-BS4-Angular-4-demo/node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts: ([object Object], [object Object], [object Object], ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for NgbModalRef in /home/rendiqi/work/SB-Admin-BS4-Angular-4-demo/node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-ref.d.ts: ([object Object], [object Object], [object Object], ?). This will become an error in Angular v5.x
`
and then report the error
`ERROR_ in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/rendiqi/work/SB-Admin-BS4-Angular-4-demo/src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
ERROR in ./src/$$_gendir async
Module not found: Error: Can't resolve '/home/rendiqi/work/SB-Admin-BS4-Angular-4-demo/src/$$_gendir/app/layout/layout.module.ngfactory.ts' in '/home/rendiqi/work/SB-Admin-BS4-Angular-4-demo/src/$$_gendir'
 @ ./src/$$_gendir async
 @ ./~/_@angular_core@4.3.6@@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi ./src/main.ts
...........
`

and the log:
[2017-09-11T04_57_44_666Z-debug.txt](https://github.com/start-angular/SB-Admin-BS4-Angular-4/files/1291436/2017-09-11T04_57_44_666Z-debug.txt)


Is my node version to high?

**Comment by akshugharge** [comment]
ng build is working awesome theme thanks
