### ISSUE TITLE
Repository made from scratch

### ISSUE THREAD

**Issue by bjakubiak** [start-angular/SB-Admin-BS4-Angular-4#112]
Hi.

I know it is your repository and you can do whatever you want with it.
It seems you initialized it from scratch losing all the previous commits. The code is still there, but it is somewhat troublesome to merge forked projects with your upstream now.

Was there any reason to reinitialize repository?
I also noticed .travis.yml dissapeared - any reason for it too?

Anyway, I appreciate your work here, this is one of the best admin dashboards for angular 2.

**Comment by nitinkrmr** [comment]
Everytime when this project is updated, we generate new project using latest CLI, which has different GIT history
That is why we lose the commits from its history.
Thank you for bringing this into our notice, we will make sure this does not happen in future
