### ISSUE TITLE
ngModel

### ISSUE THREAD

**Issue by dresoy** [start-angular/SB-Admin-BS4-Angular-4#113]
Hi guys! I'm trying to use your template, it all seams so great, but when I try to do this at the login html
`<div>`
  `<input [(ngModel)]="name" #ctrl="ngModel" required>`
  `<p>Value: {{ name }}</p>`
  `<p>Valid: {{ ctrl.valid }}</p>`
  `<button (click)="setValue()">Set value</button>`
`</div>`

I end up with: ERROR Error: Uncaught (in promise): Error: Template parse errors:
There is no directive with "exportAs" set to "ngModel" ("
`</div>`
`<div>`
    `<input [(ngModel)]="name" [ERROR ->]#ctrl="ngModel" required>`

Sorry If i'm asking something dumb, I'm new with Angular 2-4...

**Comment by nitinkrmr** [comment]
use Reactive form for login implementation instead of template driven form.
Kindly refer https://toddmotto.com/angular-2-forms-reactive

**Comment by dresoy** [comment]
Thanks for the help, this templates teachs a lot!

And for those with my beginner question, you must add

`import { ReactiveFormsModule, FormsModule } from '@angular/forms';`
in the login.module.ts.

Thanks again @nitinkrmr 👍
