### ISSUE TITLE
Can't bind to input elements

### ISSUE THREAD

**Issue by chrisplusplus** [start-angular/SB-Admin-BS4-Angular-4#116]
Even though by default the template comes with Forms module imported in app.module.ts, I still cannot bind to input elements.  Specifically, on the log in page.

Error:
Can't bind to 'ngModel' since it isn't a known property of 'input'

A quick Google search seems to indicate that everyone was able to fix this issue by adding
 import { FormsModule } from '@angular/forms';
to app.module.ts
But this is already added in the application.  Any ideas?

**Comment by nitinkumarmishra** [comment]
`import { FormsModule } from '@angular/forms'; ` in login.module.ts file and alos in import section then it will work fine

**Comment by chrisplusplus** [comment]
Thanks - I will check closed issues next time!
