### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by mschoeffler** [start-angular/SB-Admin-BS4-Angular-4#123]
I found a short hint about the license in the "package.json" file (MIT). I guess many developers prefer to have a full documentation of the license also in a separate LICENSE file. Would it be possible to add one?

**Comment by nitinwaves** [comment]
Yes it would be great.. we want to use this theme for a law-firm but bit worried about the license of this theme.. is it free to use, customize, re-brand and without keeping an credits of dev tram?

**Comment by nitinkumarmishra** [comment]
We have licence file but it's on different branch 
https://github.com/start-angular/SB-Admin-BS4-Angular-4/blob/gulp/LICENSE
use above licence file, will add it soon
