### ISSUE TITLE
problem adding Service in SignupComponent

### ISSUE THREAD

**Issue by vintots** [start-angular/SB-Admin-BS4-Angular-4#125]
here is my code and also the error message that i recieved
I already added it in the SignupModule but i always received that error in the picture
`

import { Component, OnInit } from '@angular/core';
import { routerTransition } from '../router.animations';

import { SignupService } from './signup.component.service';

@Component({
    selector: 'app-signup',
    templateUrl: './signup.component.html',
    styleUrls: ['./signup.component.scss'],
    animations: [routerTransition()],
    providers:[SignupService]
})

export class SignupComponent implements OnInit {
    user:user;
  
    constructor(signupService:SignupService) {
        console.log(signupService.register());
        this.user={
            firstName:'',
            middleName:'',
            lastName:'',
            gender:'',
            email:'',
            password:'',
            repeatPassword:''
        }
     }

    ngOnInit() { }

    signup(){
        console.log(this.user);
    }
}

interface user{
    firstName:string,
    middleName:string,
    lastName:string,
    gender:string,
    email:string,
    password:string,
    repeatPassword:string
}
`
![service_error](https://user-images.githubusercontent.com/12949379/29408129-a0110090-8379-11e7-9097-8b10bf96fbf6.PNG)

**Comment by AlainD-** [comment]
It is strange how you do things.

Instead of declaring SignupService in ServiceModule, provide it instead:
`providers: [SignupService]`

Then remove the providers from your Component definition, and adapt the import path of SignupService.

**Comment by vintots** [comment]
Thanks @AlainD-  It's now working :) i thought every time that i am going to add service i will import it in the module.

**Comment by AlainD-** [comment]
Well, Or you misunderstood your tuto or the tuto is very wrong about that (if that's the case then train by using another tutorial).
You generally provide the services in the modules (`providers` array), not import them! :-)

**Comment by vintots** [comment]
thanks again 👍 @AlainD- cheers!!
