### ISSUE TITLE
Build fail [SOLVED] Missing: SyncTestZoneSpec [SOLVED ]Tests failed [KO]

### ISSUE THREAD

**Issue by Dorian-s** [start-angular/SB-Admin-BS4-Angular-4#126]
Hello,

I'm trying to build this project but I encountered this issue:

Hash: 8680a04b76f5d071b7da
Time: 23543ms
chunk    {0} polyfills.6829d3cbeaa58ee96ca3.bundle.js
(polyfills) 255 kB {5} [initial] [rendered]
chunk    {1} scripts.1c6869de9aab67044382.bundle.js (scripts)
409 kB {5} [initial] [rendered]
chunk    {2} main.f77df68876cdb28fe1e2.bundle.js (main) 1.1 kB
{4} [initial] [rendered]
chunk    {3} styles.069ca53dd7e45c9b9708.bundle.css (styles) 122
bytes {5} [initial] [rendered]
chunk    {4} vendor.bd074f366f4d3409c7df.bundle.js (vendor) 850
kB [initial] [rendered]
chunk    {5} inline.fd280225431f0e5c8f93.bundle.js (inline) 0
bytes [entry] [rendered]

[...]

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sb-admin-cli-update@0.0.0 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sb-admin-cli-update@0.0.0 build script
'ng build --prod'.
npm ERR! Make sure you have the latest version of node.js and
npm installed.
npm ERR! If you do, this is most likely a problem with the
sb-admin-cli-update package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build --prod
npm ERR! You can get information on how to open an issue for
this project with:
npm ERR!     npm bugs sb-admin-cli-update
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sb-admin-cli-update
npm ERR! There is likely additional logging output above.

I got your project by cloning the repository. I tried to update
angular/cli but nothing changed..

Can you help me ?

BR,

**Comment by nitinkumarmishra** [comment]
Can you please update @angular-cli and then try

**Comment by Dorian-s** [comment]
Hi, 
I had already updated with @latest but nothing was changed

**Comment by nitinkumarmishra** [comment]
please attatch complete log file

**Comment by Dorian-s** [comment]
Ok, I will attach tonight. thx

**Comment by Dorian-s** [comment]
Tonight it seems to be OK ...

$ npm run build

> sb-admin-cli-update@0.0.0 build C:\SB-Admin-BS4-Angular-4
> ng build --prod

Date: 2017-08-24T17:47:54.229Z
Hash: 86bfc90552268d37e473
Time: 36753ms
chunk {0} 0.a4a04ac14b5f224a9469.chunk.js (common) 13.8 kB {14}  [rendered]
chunk {1} 1.d5fd0534ead6c8e61f75.chunk.js () 483 kB {14}  [rendered]
chunk {2} 2.433267922faf0fea2673.chunk.js () 246 kB {14}  [rendered]
chunk {3} 3.955066c1dcb6468be61e.chunk.js () 8.37 kB {14}  [rendered]
chunk {4} 4.310b364721b366889730.chunk.js () 4.3 kB {14}  [rendered]
chunk {5} 5.3708f30f454405f6a154.chunk.js () 7.68 kB {14}  [rendered]
chunk {6} 6.8a262cdce439f2a4ff3a.chunk.js () 50.5 kB {14}  [rendered]
chunk {7} 7.e32e7969a592cc1e0ce9.chunk.js () 42.1 kB {14}  [rendered]
chunk {8} 8.bb6e7bb7ca85d1396d5c.chunk.js () 24.6 kB {14}  [rendered]
chunk {9} 9.e23f82178c31dfca0c6b.chunk.js () 26.6 kB {14}  [rendered]
chunk {10} 10.2da84dba43decedccf39.chunk.js () 60.6 kB {14}  [rendered]
chunk {11} 11.8be7d2f1971a33ed26f9.chunk.js () 37.4 kB {14}  [rendered]
chunk {12} 12.bccc1699d1aecba9fcd1.chunk.js () 1.22 kB {14}  [rendered]
chunk {13} polyfills.f159f821e4969dc721ea.bundle.js (polyfills) 97.4 kB {18} [initial] [rendered]
chunk {14} main.169c4b4429eb6a0c0445.bundle.js (main) 7.78 kB {17} [initial] [rendered]
chunk {15} scripts.350af54e104f7b0542a7.bundle.js (scripts) 409 kB {18} [initial] [rendered]
chunk {16} styles.069ca53dd7e45c9b9708.bundle.css (styles) 167 kB {18} [initial] [rendered]
chunk {17} vendor.5b40d4da660f2e6daba8.bundle.js (vendor) 506 kB [initial] [rendered]
chunk {18} inline.a977fc7d8982b8ede544.bundle.js (inline) 1.8 kB [entry] [rendered]

But When I test other job, the tests failed

$ npm test

> sb-admin-cli-update@0.0.0 test C:\SB-Admin-BS4-Angular-4
> ng test

 10% building modules 2/2 modules 0 active24 08 2017 19:48:49.593:WARN [karma]: No captured browser, open http://localhost:9876/
24 08 2017 19:48:49.593:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
24 08 2017 19:48:49.593:INFO [launcher]: Launching browser Chrome with unlimited concurrency
24 08 2017 19:48:49.625:INFO [launcher]: Starting browser Chrome                                                                                                                                                                     24 08 2017 19:49:01.742:WARN [karma]: No captured browser, open http://localhost:9876/
24 08 2017 19:49:02.693:INFO [Chrome 60.0.3112 (Windows 7 0.0.0)]: Connected on socket gbJXF9Xfr4Uuy9o2AAAA with id 65488996
Chrome 60.0.3112 (Windows 7 0.0.0) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:42471
Chrome 60.0.3112 (Windows 7 0.0.0) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:42471

Chrome 60.0.3112 (Windows 7 0.0.0) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:42471

I am looking why..

**Comment by Dorian-s** [comment]
Can you please give me your configuration ? 

$ ng -v
Your global Angular CLI version (1.3.1) is greater than your local
version (1.2.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.1
node: 6.11.2
os: win32 x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.6
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.2.1
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5

**Comment by Dorian-s** [comment]
Test ran by modifying the test.ts :
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';

the order is important.

But another problem .... all tests failed : 
28 08 2017 19:12:35.989:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
28 08 2017 19:12:35.989:INFO [launcher]: Launching browser Chrome with unlimited concurrency
28 08 2017 19:12:36.005:INFO [launcher]: Starting browser Chrome
28 08 2017 19:12:47.427:WARN [karma]: No captured browser, open http://localhost:9876/
28 08 2017 19:12:48.681:WARN [karma]: No captured browser, open http://localhost:9876/
28 08 2017 19:12:48.761:INFO [Chrome 60.0.3112 (Windows 7 0.0.0)]: Connected on socket VnxLBi8fvIQPk6mTAAAA with id 65803269
Chrome 60.0.3112 (Windows 7 0.0.0) AppComponent should create the app FAILED
        TypeError: Cannot read property 'assertPresent' of undefined
            at resetFakeAsyncZone (http://localhost:9876/_karma_webpack_/vendor.bundle.js:92292:18)
            at Object.<anonymous> (http://localhost:9876/_karma_webpack_/vendor.bundle.js:92989:9)
            at ZoneQueueRunner.webpackJsonp.../../../../zone.js/dist/jasmine-patch.js.jasmine.QueueRunner.ZoneQueueRunner.execute (http://localhost:9876/_karma_webpack_/vendor.bundle.js:42518:42)
Chrome 60.0.3112 (Windows 7 0.0.0): Executed 1 of 32 (1 FAILED) (0 secs / 0.094 secs)

**Comment by Dorian-s** [comment]
Could you please have a look ?

**Comment by Dorian-s** [comment]
all ok for me

**Comment by zarnifoulette** [comment]
Hello, 

Did you find a solution for that ? :
Error: Found the synthetic property @routertransition. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application at checkNoSyntheticProp
