### ISSUE TITLE
Components not work!

### ISSUE THREAD

**Issue by Tricar** [start-angular/SB-Admin-BS4-Angular-4#136]
Great Job, but when I try access to Components Menu, and I have a error: 
`ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'up' since it isn't a known property of 'div'. ("
            </div>
            <div class="col text-right">
                <div ngbDropdown [ERROR ->][up]="true"` Please help me

**Comment by xiaosan0318** [comment]
I have this problem, too

**Comment by nitinkumarmishra** [comment]
use `placement` instead of up,
refer https://ng-bootstrap.github.io/#/components/dropdown/api
