### ISSUE TITLE
How to add .swf file 

### ISSUE THREAD

**Issue by liuziyuan** [start-angular/SB-Admin-BS4-Angular-4#137]
when  i require a .swf file .then tell me "You may need an appropriate loader to handle this file type."
const swf = require('../../../../assets/video-js.swf');

I don't look webpack config file .how i  can add webpack plugin ?

**Comment by nitinkumarmishra** [comment]
You need to use System.import to import a file dynamically or you can inject your file in script array of .angular-cli.json file

**Comment by Shraddhavarang** [comment]
I have injected .swf but still showing me following error

ERROR in ./node_modules/ng2-webcam/lib/fallback/jscam.swf
Module parse failed: D:\VideoDemo\node_modules\ng2-webcam\lib\fallback\jscam.swf Unexpected character ' (1:3)
You may need an appropriate loader to handle this file type



![video](https://user-images.githubusercontent.com/30266175/32156730-1e2ffe84-bd65-11e7-979c-9cae72dfb3fd.png)
