### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by benj-Jansen** [start-angular/SB-Admin-BS4-Angular-4#140]
Hi there,

it would be rly helpful to know which license this awesome repo has.

Thanks

**Comment by benj-Jansen** [comment]
License got added, thanks alot and please keep up the great work guys!

P.S. If you write License in capital letters, github should auto include the license in a filed in top right

**Comment by shwetapal** [comment]
@benj-Jansen Thanks for the appreciation. And also the license file has been renamed.
