### ISSUE TITLE
Can't access route directly - Its give 404 error

### ISSUE THREAD

**Issue by salih0313** [start-angular/SB-Admin-BS4-Angular-4#141]
if i access directly Form Screen, i am getting 404 error.

http://rawgit.com/start-angular/SB-Admin-BS4-Angular-4/master/dist/forms

Any solution? Am using same template to my project. Facing the same isssues.

**Comment by salih0313** [comment]
Any suggestion please?

**Comment by nitinkumarmishra** [comment]
This problem with the github server for a dedicated server it would not happen.
you need to setup the `Redirect Rule` i.e for Apache server all the redirect rule are defined in the .htaccess file something like that.
