### ISSUE TITLE
can not disable initialNavigation

### ISSUE THREAD

**Issue by suranan** [start-angular/SB-Admin-BS4-Angular-4#145]
hi everyone, I try to disable initialNavigation in app-routing.module.ts file but there are nothing show when I run program

import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { AuthGuard } from './shared';

const routes: Routes = [
    {
        path: '',
        loadChildren: './layout/layout.module#LayoutModule',
        canActivate: [AuthGuard]
    },
    { path: 'login', loadChildren: './login/login.module#LoginModule' },
    { path: 'signup', loadChildren: './signup/signup.module#SignupModule' },
    { path: 'not-found', loadChildren: './not-found/not-found.module#NotFoundModule' },
    { path: '**', redirectTo: 'not-found' }
];

@NgModule({
    imports: [RouterModule.forRoot(routes, {initialNavigation: false})],
    exports: [RouterModule]
})
export class AppRoutingModule { }

thank you

**Comment by nitinkumarmishra** [comment]
take a look at the AuthGuard defind in the defined the `shared/guard` folder. you can remove that from there. also take a look at the `layout.component.ts`  and remove lines defined in the ngOnInit interface
