### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by nsankaranarayanan** [start-angular/SB-Admin-BS4-Angular-4#147]
I couldn't find enough documentation on how to use this template.
Could you please help me with the following?
1. Make the startup page as login?
2. Where to add the web service call to authenticate and set the token?
3. Users should not be able to hit dashboard or any other page without logging in.
4. How to handle logout?
5. How to integrate login using OAuth and JWT using Auth0

**Comment by nitinkumarmishra** [comment]
1: Use guard for authenticated route, it's already there.
2: Add all the services in the shared/services dir and use interceptor to add token.
3: Guard will handle this.
4: Remove token from localStorage on logout.
5: use 3rd party packages like https://github.com/0xMatt/ngx-oauth-client
