### ISSUE TITLE
How to make a new component based on layout

### ISSUE THREAD

**Issue by tunathoni** [start-angular/SB-Admin-BS4-Angular-4#148]
I want to make a component using cli like this : 
`ng g component layout/users`

 also add new navigation in sidebar : 
```
<a [routerLink]="['/users']" [routerLinkActive]="['router-link-active']" class="list-group-item">
            <i class="fa fa-fw fa-bar-chart-o"></i>&nbsp;{{ 'Users' | translate }}
 </a>
```

then i added in layout-routing.module.ts : 

```
children: [
            { path: 'dashboard', loadChildren: './dashboard/dashboard.module#DashboardModule' },
            { path: 'users', loadChildren: './users/users.module#UsersModule' },
            { path: 'charts', loadChildren: './charts/charts.module#ChartsModule' },
            { path: 'tables', loadChildren: './tables/tables.module#TablesModule' },
            { path: 'forms', loadChildren: './form/form.module#FormModule' },
            { path: 'bs-element', loadChildren: './bs-element/bs-element.module#BsElementModule' },
            { path: 'grid', loadChildren: './grid/grid.module#GridModule' },
            { path: 'components', loadChildren: './bs-component/bs-component.module#BsComponentModule' },
            { path: 'blank-page', loadChildren: './blank-page/blank-page.module#BlankPageModule' },
        ]
```

but after i run it still got an error. 
```
ERROR Error: Uncaught (in promise): Error: Cannot find 'UsersModule' in './users/users.module'
```
can you tell me how to make a new component using cli in this template ? thank you

**Comment by ganxo** [comment]
Hi, I have the same problem.
have you been able to solve it?

**Comment by pbrink231** [comment]
The commands I use are:
'ng g module layout/threed' (makes the module)
'ng g component layout/threed -m=layout/threed/threed.module.ts` (creates component and adds the link to the module)
Then I would copy aother xxxx-routing.module.ts and paste it into that folder.  Modify all relations you need to fix.
In your component.ts make sure to add the routerTransition.  You can see it in the other layout pages.
In your layout-routing.module.ts file add the load child

The other problem I have now is that the new page loads but does not clear the old page so there is one more thing I am missing.  From then on it no longer clears any previous page.  I had it working and now it is not so not sure why.
