### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by ErisoHV** [start-angular/SB-Admin-BS4-Angular-4#149]
Hi! I'm following this steps:

```
$ git clone https://github.com/start-angular/SB-Admin-BS4-Angular-4
$ cd SB-Admin-BS4-Angular-4
$ npm install
$ npm start
```

When I execute **npm start**, I get this;

```
> ng serve --ec true --port 4200
@angular/compiler-cli@4.4.6 requires typescript@'>=2.1.0 <2.4.0' but 2.5.3 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.
Please run the following command to install a compatible version of TypeScript.
    npm install typescript@'>=2.1.0 <2.4.0'
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
...
webpack: Compiled successfully.
```
But, when I try to access:  http://localhost:4200/ I get:

_Can not access this website
The localhost page has rejected the connection.
ERR_CONNECTION_REFUSED_

I'm using:
npm 3.10.10
angular/cli: 1.4.8
node: 6.11.3
os: win32 x64
angular/animations: 4.4.6
angular/common: 4.4.6
angular/compiler: 4.4.6
angular/core: 4.4.6
angular/forms: 4.4.6
angular/http: 4.4.6
angular/platform-browser: 4.4.6
angular/platform-browser-dynamic: 4.4.6
angular/router: 4.4.6
angular/cli: 1.4.8
angular/compiler-cli: 4.4.6
angular/language-service: 4.4.6
typescript: 2.5.3

Please help

**Comment by nitinkumarmishra** [comment]
It is a versioning problem just delete `^` char from package.json file, remove node_modules and then reinstall all the packages will solve this problem.

**Comment by ErisoHV** [comment]
Thanks @nitinkumarmishra, but that didn't work for me.

My problem was my host's configuration. I tried with: `ng serve --port 4200 --host 127.0.0.1` and worked.
