### ISSUE TITLE
Errors on clean install.

### ISSUE THREAD

**Issue by DocBradfordSoftware** [start-angular/SB-Admin-BS4-Angular-4#159]
I followed the instructions, however, i had errors on "npm start".

I had to install the following
```
npm i webpack --save-dev
npm install typescript@'>=2.1.0 <2.4.0'
```

After that it worked fine.

**Comment by fabiomartino** [comment]
looks like the upcoming cli version (starting from v1.5 RC6) fix this issue.
https://github.com/angular/angular-cli/releases/tag/v1.5.0-rc.6
