### ISSUE TITLE
i want to this angular4 project convert to Tomcat war file with backend java

### ISSUE THREAD

**Issue by MaghizMannan** [start-angular/SB-Admin-BS4-Angular-4#160]
I want to convert angular 4 project into tomcat war file. but loadChildren is not working when converted. Can you please guide us ASAP. is it possible to convert? First page is loading but dashboard page is not loading after conversion.

**Comment by nitinkumarmishra** [comment]
Deploy both the project on different server, front end on nginx and backend on Apache tomcat.
Configure reverse proxy on nginx server.

**Comment by MaghizMannan** [comment]
Thank you very much. We will try and let you know.

On 1 Nov 2017 17:03, "Nitin Kumar Mishra" <notifications@github.com> wrote:

Closed #160
<https://github.com/start-angular/SB-Admin-BS4-Angular-4/issues/160>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/start-angular/SB-Admin-BS4-Angular-4/issues/160#event-1320818446>,
or mute the thread
