### ISSUE TITLE
Layout module not working when used as sub module

### ISSUE THREAD

**Issue by baldassarreFe** [start-angular/SB-Admin-BS4-Angular-4#80]
I was trying to use the layout module as a a sub module and access it like:
```
mywebsite.com/layout/dashboard
mywebsite.com/layout/charts
...
```

However the definitions of the routes only allow for the layout module to be accessed with "first level" routes, like:
```
mywebsite.com/dashboard
mywebsite.com/charts
...
```

I realize that for the demo this is probably the wanted behavior, but it is a constraining choice for further development. For this reason I think it would be better to have it integrated in the repo rather than having to change it manually later.

I am submitting a PR that allows to have routes like in the first example. I am quite sure that no other modification is necessary, apart from the routing modules and some href in the html to preserve the pre-existing navigation links.

**Comment by nitinkumarmishra** [comment]
i think showing `layout` in url is not a good idea.

**Comment by baldassarreFe** [comment]
I get your point and I agree that having "layout" in the url is not nice to see, at least in the example web page.

In my application however I need to have a "home" route and some "home/dashboard", "home/charts" sub routes that are only accessible if the user is logged in. For this reason it was practical to set up a ```canActivate``` guard that would prevent access to everything under "home". Something as simple as adding:

**app-routing.module.ts**
```
{ path: 'layout', 
  loadChildren: './layout/layout.module#LayoutModule', 
  canActivate: [AuthGuard]},
```

**auth-guard.service.ts** (thanks to the StackOverflow user that posted this code)
```
@Injectable()
export class AuthGuard implements CanActivate {

  constructor(private router: Router, private loginService: LoginService) { }

  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
    if (this.loginService.loggedIn) {
      return true;
    } else {
      this.router.navigate(['/login'], {queryParams: {returnUrl: state.url}});
      return false;
    }
  }
}
```

You can see how this behavior would be trickier to implement if the main route of the application was simply identified with an empty string.

**Comment by nitinkumarmishra** [comment]
Correct `home` looks good, i will add it. Thanks @baldassarreFe
