### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by aldrindizonh** [start-angular/SB-Admin-BS4-Angular-4#82]
Hello Im having an error when i run npm install

[fsevents] Success: "/Users/adizon/Documents/development/ImpAngular4/node_modules/@angular/cli/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/common@4.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/forms@4.0.1 wants @angular/common@4.0.1
npm ERR! peerinvalid Peer @angular/platform-browser@4.0.1 wants @angular/common@4.0.1
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@4.0.1 wants @angular/common@4.0.1
npm ERR! peerinvalid Peer @angular/router@4.0.1 wants @angular/common@4.0.1
npm ERR! peerinvalid Peer @ng-bootstrap/ng-bootstrap@1.0.0-alpha.22 wants @angular/common@^2.3.1 || ^4.0.0
npm ERR! peerinvalid Peer ng2-charts@1.5.0 wants @angular/common@^2.3.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adizon/Documents/development/ImpAngular4/npm-debug.log

**Comment by nitinkumarmishra** [comment]
upgrade your node version to latest

**Comment by aldrindizonh** [comment]
I update the node it works! thanks but when i run npm start it shows below error

ERROR in multi ./~/font-awesome/css/font-awesome.css ./src/styles/app.scss
Module not found: Error: Can't resolve 'style-loader' in '/Users/adizon/Documents/development/SB-Admin-BS4-Angular-4'
 @ multi ./~/font-awesome/css/font-awesome.css ./src/styles/app.scss

ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in '/Users/adizon/Documents/development/SB-Admin-BS4-Angular-4'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in '/Users/adizon/Documents/development/SB-Admin-BS4-Angular-4'
 @ multi ./src/polyfills.ts

ERROR in multi ./~/font-awesome/css/font-awesome.css ./src/styles/app.scss
Module not found: Error: Can't resolve 'style-loader' in '/Users/adizon/Documents/development/SB-Admin-BS4-Angular-4'
 @ multi ./~/font-awesome/css/font-awesome.css ./src/styles/app.scss

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'raw-loader' in '/Users/adizon/Documents/development/SB-Admin-BS4-Angular-4':
  Error: Can't resolve 'raw-loader' in '/Users/adizon/Documents/development/SB-Admin-BS4-Angular-4'
  
  - compiler.js:76 
    [SB-Admin-BS4-Angular-4]/[cli]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:280 Compiler.<anonymous>
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/lib/Compiler.js:280:10
  
  - Compiler.js:480 
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/lib/Compiler.js:480:13
  
  - Tapable.js:138 next
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/[tapable]/lib/Tapable.js:138:11
  
  - CachePlugin.js:62 Compiler.<anonymous>
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/lib/CachePlugin.js:62:5
  
  - Tapable.js:142 Compiler.applyPluginsAsyncSeries
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/[tapable]/lib/Tapable.js:142:13
  
  - Compiler.js:477 
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/lib/Compiler.js:477:10
  
  - Tapable.js:138 next
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/[tapable]/lib/Tapable.js:138:11
  
  - suppress-entry-chunks-webpack-plugin.js:35 Compilation.compilation.plugin
    [SB-Admin-BS4-Angular-4]/[@angular]/cli/plugins/suppress-entry-chunks-webpack-plugin.js:35:17
  
  - Tapable.js:142 Compilation.applyPluginsAsyncSeries
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/[tapable]/lib/Tapable.js:142:13
  
  - Compilation.js:640 self.applyPluginsAsync.err
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/lib/Compilation.js:640:19
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:631 self.applyPluginsAsync.err
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/lib/Compilation.js:631:11
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:626 self.applyPluginsAsync.err
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/lib/Compilation.js:626:10
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [SB-Admin-BS4-Angular-4]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131:46
  

webpack: Failed to compile.

**Comment by nitinkumarmishra** [comment]
follow steps: 
1: `npm install -g @angular-cli/core`
2: install node (latest version)
3: remove node_modules and then `npm install`
4: npm start

**Comment by aldrindizonh** [comment]
it works bro! Thanks
