### ISSUE TITLE
npm run build.prod failing on SB-Admin-BS4-Angular-2

### ISSUE THREAD

**Issue by srivastavapriyank** [start-angular/SB-Admin-BS4-Angular-4#83]
Hi,
I am getting an error while "npm run build.prod"

code ELIFECYCLE
npm ERR! SB-Admin-BS4-Angular-2@0.0.0 build.prod: `gulp build.prod --color --config-env prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the SB-Admin-BS4-Angular-2@0.0.0 build.prod script 'gulp build.prod --color --config-env prod'.

When I run this for npm run build.dev, this works well. Is there anything I am missing, I havent changed anything on the config files. I have SB admin BS4 Anugular 2, please help as I need to deploy my app to prod

**Comment by nitinkumarmishra** [comment]
run `gulp build.prod`

**Comment by srivastavapriyank** [comment]
Hi,
tried gulp build.prod but not working. The process ends with the last step
[17:47:36] Starting 'build.js.prod'...

and in dist folder I see tmp folder with app and other files while assets and css are copied to dist/prod.
When I run the command for gulp build.dev followin additional steps are shown
[17:48:34] Finished 'build.js.dev' after 5.24 s
[17:48:34] Starting 'build.index.dev'...
[17:48:34] gulp-inject 2 files into index.html.
[17:48:34] gulp-inject 4 files into index.html.
[17:48:34] gulp-inject 2 files into index.html.
[17:48:34] Finished 'build.index.dev' after 96 ms
[17:48:34] Finished 'build.dev' after 12 s 

these above steps are not executed for build.prod

Am I missing some setting to generate code for deployment?

**Comment by srivastavapriyank** [comment]
From the npm-debug.log


0 info it worked if it ends with ok
1 verbose cli [ '/Users/ankitsahu/.nvm/versions/node/v7.2.1/bin/node',
1 verbose cli   '/Users/ankitsahu/.nvm/versions/node/v7.2.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build.prod' ]
2 info using npm@3.10.10
3 info using node@v7.2.1
4 verbose run-script [ 'prebuild.prod', 'build.prod', 'postbuild.prod' ]
5 info lifecycle SB-Admin-BS4-Angular-2@0.0.0~prebuild.prod: SB-Admin-BS4-Angular-2@0.0.0
6 silly lifecycle SB-Admin-BS4-Angular-2@0.0.0~prebuild.prod: no script for prebuild.prod, continuing
7 info lifecycle SB-Admin-BS4-Angular-2@0.0.0~build.prod: SB-Admin-BS4-Angular-2@0.0.0
8 verbose lifecycle SB-Admin-BS4-Angular-2@0.0.0~build.prod: unsafe-perm in lifecycle true
9 verbose lifecycle SB-Admin-BS4-Angular-2@0.0.0~build.prod: PATH: /Users/ankitsahu/.nvm/versions/node/v7.2.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/ankitsahu/code/velvelbash/velvetbash-admin/node_modules/.bin:/Users/ankitsahu/.nvm/versions/node/v7.2.1/bin:/Applications/XAMPP/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/mongodb/bin:/Applications/apache-maven-3.3.9/bin
10 verbose lifecycle SB-Admin-BS4-Angular-2@0.0.0~build.prod: CWD: /Users/ankitsahu/code/velvelbash/velvetbash-admin
11 silly lifecycle SB-Admin-BS4-Angular-2@0.0.0~build.prod: Args: [ '-c', 'gulp build.prod --color --config-env prod' ]
12 silly lifecycle SB-Admin-BS4-Angular-2@0.0.0~build.prod: Returned: code: 1  signal: null
13 info lifecycle SB-Admin-BS4-Angular-2@0.0.0~build.prod: Failed to exec build.prod script
14 verbose stack Error: SB-Admin-BS4-Angular-2@0.0.0 build.prod: `gulp build.prod --color --config-env prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/ankitsahu/.nvm/versions/node/v7.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/ankitsahu/.nvm/versions/node/v7.2.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid SB-Admin-BS4-Angular-2@0.0.0
16 verbose cwd /Users/ankitsahu/code/velvelbash/velvetbash-admin
17 error Darwin 14.5.0
18 error argv "/Users/ankitsahu/.nvm/versions/node/v7.2.1/bin/node" "/Users/ankitsahu/.nvm/versions/node/v7.2.1/bin/npm" "run" "build.prod"
19 error node v7.2.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error SB-Admin-BS4-Angular-2@0.0.0 build.prod: `gulp build.prod --color --config-env prod`
22 error Exit status 1
23 error Failed at the SB-Admin-BS4-Angular-2@0.0.0 build.prod script 'gulp build.prod --color --config-env prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the SB-Admin-BS4-Angular-2 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build.prod --color --config-env prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs SB-Admin-BS4-Angular-2
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls SB-Admin-BS4-Angular-2
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by nitinkumarmishra** [comment]
try with node 4.4.4,
https://nodejs.org/download/release/v4.4.4/
steps: 
1: rm -fR node_modules
2: npm install
3: gulp build.pord
if you need old one(using gulp) go to https://github.com/start-angular/SB-Admin-BS4-Angular-4/tree/gulp

**Comment by srivastavapriyank** [comment]
I am on node 7.2.1, are you saying I need to downgrade my node and reinstall everything?

**Comment by nitinkumarmishra** [comment]
yes because it is quite old

**Comment by srivastavapriyank** [comment]
Reinstalling 4.4.4 node didnt solve the problem. I think there is something else which is stopping the build process for prod.
What are the steps I need to follow to set up prod build from the admin?
