### ISSUE TITLE
Failed to load in IE 11

### ISSUE THREAD

**Issue by hfye** [start-angular/SB-Admin-BS4-Angular-4#84]
The loading bar is hanging when start it from Internet explorer 11 (version 11.0.9600)

In the debugger window, it shows the error message "Unable to get property 'apply' of undefined or null reference" inside the following method:

-vendor.bundle.js
function combine(options) {
    return ((Object)).assign.apply(((Object)), [{}].concat(options));
}

but there is no problem with Chrome or firefox.

**Comment by nitinkumarmishra** [comment]
added IE support
