### ISSUE TITLE
Maybe a Route Problem...

### ISSUE THREAD

**Issue by QJesus** [start-angular/SB-Admin-BS4-Angular-4#89]
Your [Demo](http://rawgit.com/start-angular/SB-Admin-BS4-Angular-4/master/dist/)  WebSite

When I Press F5 to reload page, it will be a new page and noly shows "404: Not Found" .

Will it be a route problem ?

**Comment by nitinkumarmishra** [comment]
This is problem with git server, it will work fine with apache server there is a .htaccess file which will be used for the serving the index.html file.

**Comment by QJesus** [comment]
`ng build --prod --aot` Error
