### ISSUE TITLE
problem with angular

### ISSUE THREAD

**Issue by mukeem1** [start-angular/SB-Admin-BS4-Angular-4#90]
> sb-admin@0.0.0 start D:\git\dashboard\dashboard
> grunt serve

'grunt' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! sb-admin@0.0.0 start: `grunt serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sb-admin@0.0.0 start script 'grunt serve'.
npm ERR! This is most likely a problem with the sb-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt serve
npm ERR! You can get their info via:
npm ERR!     npm owner ls sb-admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\git\dashboard\dashboard\npm-debug.log

**Comment by nitinkumarmishra** [comment]
update your node version to latest,
1: delete node_modules
2: npm install
3: npm start
it will work fine.

**Comment by mukeem1** [comment]
not working
again following error occurring 

D:\git\dashboard\dashboard\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\git\dashboard\dashboard\npm-debug.log

**Comment by nitinkumarmishra** [comment]
update your node version to latest
![image](https://cloud.githubusercontent.com/assets/14124584/25940682/8c06db0a-3654-11e7-811d-38362fa28c23.png)
