### ISSUE TITLE
add persian translation

### ISSUE THREAD

**Issue by webnegar** [start-angular/SB-Admin-BS4-Angular-4#94]
hi, you can add persian translation like this:

{
    "dashboard": "داشبورد",
    "charts": "چارت ها",
    "tables": "جداول",
    "froms": "فرم ها",
    "boostrapElement": "عنصر بوتسترپ",
    "boostrapGrid": "جدول بوتسترپ",
    "component": "کامپوننت",
    "menu": "منو",
    "submenu": "زیر منو",
    "blankpage": "صفحه خالی",
    "moretheme": "تم های بیشتر",
    "downloadNow": "دانلود",
    "language": "زبان"
}

**Comment by nitinkumarmishra** [comment]
Done
