### ISSUE TITLE
Sidebar menu under md size doesn't hide after clik on menu item

### ISSUE THREAD

**Issue by tzecat** [start-angular/SB-Admin-BS4-Angular-4#95]
Resize in a minimal view (ie.mobile device),
Click on 3-bar menu to expand menu
Choose an item menu
Menu doesn't desappear by itself 
Need to reclick on the 3-bar icon menu.

Could we make something to auto-hide menu after choice&click ?

Thank you for your very great job !.
Regards. thierry

**Comment by runtop** [comment]
need this feature very much ！

**Comment by brama051** [comment]
Check out the `HeaderComponent` and look what `toggleSidebar()` method does. Copy and paste that same method into the `SidebarComponent` and call it on click event like this: `(click)="toggleSidebar()"`

**Comment by nitinkumarmishra** [comment]
Fixed
